layout_spectrum: 1
typography_spectrum: 0.9408602
color:
  saturation: 1
  lightness: 0.3722197
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#03B1AA'
    - '#B3E4E3'
    - '#35B9B4'
    - '#76C6C4'
  rhythmicContrast: 0.6182795
name: 'Dysautonomia '
